### PR TITLE
Update runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by obiwankennedy** [comment]
bot build

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
I think the better approach would include updating the package from upstream, which include using the WebEngine base app and a change in the dependencies (not sure kdegames is still needed - it doesn't build with the newer runtime in the version that is being used)

**Comment by hfiguiere** [comment]
And `qmake` seems unable to find the WebEngine when using the base app.

**Comment by obiwankennedy** [comment]
The use of libkdegames was a way to get a lot of dependencies  at once. There should be a way to make it easier.

**Comment by hfiguiere** [comment]
This works.

**Pull request merged**
